### ISSUE TITLE
Ex01_setup_question

### ISSUE THREAD

**Issue by K-Fujita-onkyo** [s1290117-Sugaya/CG_exercises#1]
おはようございます。CGのTAをしている藤田と申します。setup課題の提出ありがとうございます。これからは演習(授業範囲)の理解度をチェックするためにissuesに簡単な質問をあなたにさせていただきます。(issuesに質問を要求しない場合もあります。)また、修正箇所がある場合指摘いたします。即座に修正をお願いいたします。

では以下の質問に答えてください。

Q1. 演習のgitのレポジトリ作成に関して、Web pageではレポジトリの名前を“CG_exercises”と指定されていますが、なぜ違う名前なのでしょうか？説明してください。(Reference: https://web-int.u-aizu.ac.jp/~fayolle/teaching/cg/exercises/setup_files/howto_github.pdf)

Q2. display()のglBegin()とglEnd()を使ってどのようにそれぞれの線を描いたかを説明してください。

修正箇所1: GitHubのレポジトリ名を”CG_exercises”に変更してください。

**Comment by s1290117-Sugaya** [comment]
Q1. 確認不足でした。レポジトリ名をCG_exercisesに変更しました。
Q2. glBegin()でプリミティブ形式をGL_LINE_STRIPに設定。glBegin()とglEnd()の間に、forループで全ての点を指定して線をプロットしている。

**Comment by K-Fujita-onkyo** [comment]
返信ありがとうございます。

そうです。座標で線を描くためにGL_LINE_STRIPに設定、そしてそれぞれの点と点を繋ぐためにfor文を回して繋いでいきます。

次の課題は難しいかと思いますが解けた時とても気持ちいいのでぜひ頑張ってください。
