### ISSUE TITLE
About CG Ex02 "Transform"

### ISSUE THREAD

**Issue by K-Fujita-onkyo** [s1290117-Sugaya/CG_exercises#2]
お世話になっております。
CG論のTA、藤田でございます。

この度、Ex02の提出ありがとうございます。
プログラムを拝見したところ、修正点が１箇所ございました。

<<<修正点>>>

1. drawMultipleCopies()にて再帰で2分木の処理をされていますが問題文には階層を変更できるようなプログラムを作成すると書かれていますので、その機能を追加してください。(ヒント：keyboard()で変更できるようにすればいい)

修正していただけますと、課題の点数が上がります。
提出期限を多少超えても構いません。
修正が終わり次第、issuesに返信していただくようお願いいたします。

同様に理解度チェックのため、以下の質問に対する回答をするようお願いいたします。

Q1. 再帰を用いて2分木を実装していただきましたが、簡単でいいのでどのようにプログラムを作成したか説明をしてください。
Q2. PerspectiveとOrthogonalの違いを簡単でいいので教えてください。

以上、よろしくお願いいたします。

**Comment by s1290117-Sugaya** [comment]
修正：nで階層数の減少、Nで増加をさせるように修正しました。

Q1. glPushMatrix()で現在の座標系を行列スタックに保存する。座標系を縮小また左下に移動し、正20面体を描画、その正20面体について再帰的呼び出しをする。その後座標系を右に移動し、正20面体を描画、その正20面体について再帰的呼び出しをする。最後にglPopMatrix()で元の座標系に戻す。

Q2. Perspectiveではカメラからの遠近を考慮して、遠いものは小さく、近いものは大きく表示される。それに対しOrthogonalは遠近を考慮せず、遠いものであろうと近いものであろうと同じ大きさで表示される。

**Comment by K-Fujita-onkyo** [comment]
迅速な修正ありがとうございます。
先ほど確認したところうまくできています。
また理解度チェックでQ1の通りに動かしていることがプログラムから読み取れたのでOKです。
Q2も解答としてあっています。
これで演習の点数をつけさせていただきます。
以上、次の演習も頑張ってください。
