### ISSUE TITLE
CG論 Ex05 Meshについて

### ISSUE THREAD

**Issue by K-Fujita-onkyo** [s1290117-Sugaya/CG_exercises#4]
お疲れ様です。
CG論TAの藤田です。

先ほどあなたのプログラムを拝見させていただきました。

まず、前回の演習からホワイトボードに課題に関する全てのファイル(ヘッダーファイル、offファイルも含む)を提出してくださいと報告しましたがなぜ提出されていないのでしょうか？

あと確認したところ、Task 2-2: Heat diffusionにて動作しないことが判明しました。
その原因が1点あります。以下で修正点をまず確認してください。

# 修正点

## Laplacian smoothingをした後にvertex normalを再計算していない。

まず、あなたのプログラムを以下に提示します。

https://github.com/s1290117-Sugaya/CG_exercises/blob/69366e218ed33802d35d1091e5a6e6a1a64aa31a/ex05/task2/TriangleMesh.c#L438C1-L457C2

あなたのプログラムを見る限り、tri_meshのverticesを再計算していることがわかりますが、その後にvertices全てにおいてvertex normalを一切計算されていません。
なのでvertex normalを計算するコードをtri_meshのverticesが全て計算し終わった後に挿入してください。
関数はプログラムの中にすでに存在するので新しく作る必要がありません。自分で探してください。

# Task

あなたのやるべきことを以下に記載いたします。
- プログラムの修正をし、GitHubのレポジトリに再提出及びissuesに修正した内容及び自分で作成したheatStep()の説明をすること。
    - 期限は採点の都合上27日の23:59までとします。
    - 遅れて提出した場合、採点されない可能性があります。
    - 修正した後、課題に関する全てのファイルを必ず提出してください。
- 理解度チェックの質問に答えてください。
    - Laplacian smoothingについて説明してください。
    - なぜvertex normalとface normalの違いでGouraud shadingとFlat shadingのように全然違うshadingがされるのか説明してください。

以上

**Comment by s1290117-Sugaya** [comment]
・変更: heatStep()の最後にcomputeVertexNormals()を呼ぶことで各頂点の法線ベクトルを再計算させるよう変更しました。
・heatStep()の内容: ある頂点について、それに隣接した頂点の平均との差を求める。求めた差に0<λ<1(ここでは0.99とした)を掛け、それを頂点に足す。この処理を全ての頂点に対し行っている。
・Laplacial smoothing: 図形を滑らかにする手法であり、各頂点をそれに隣接する頂点の平均に置き換えることで、ノイズを少なくする。講義で扱ったものについては、頂点に、それに隣接した頂点の平均とその頂点との差に0<λ<1を掛けたものを足している。この場合、λの値によって変化の度合いを調整できる。
・face normal、vertex normalによる違い: face normalでは1つの面に対し法線が1つ存在する。それに対しvertex normalは1つの頂点に法線が1つ存在する。陰影はこの法線から計算される。face normalでは面の陰影は一定、vertex normalでは各頂点が補間されることで面の内部においても陰影が変化する。

**Comment by K-Fujita-onkyo** [comment]
修正確認しました。
しっかりできています。
また、理解度チェックもOKです。
テスト頑張ってください。
